broker:
  dns:
    - "8.8.8.8"
  expose:
    - "5672"
  ports:
    - "5672:5672"
  image: "rabbitmq:3.5.3"
worker1:
  dns:
    - "8.8.8.8"
  image: mlacaud/msstreamworker
  environment:
    - "BROKER_ADDR=147.210.128.116:5672"
yop_server:
  dns:
    - "8.8.8.8"
  image: mlacaud/yop_server
  ports:
    - "8085:8085"
  volumes:
    - ../Server/filesServer:/go/filesServer/
    - ./:/go/settings/
  environment:
    - "MY_ADDR=147.210.128.116:8085"
    - "BROKER_ADDR=147.210.128.116:5672"